param(
    [string]$Root = (Join-Path $PSScriptRoot "..")
)

. (Join-Path $PSScriptRoot "slide-tools.ps1")

$resolvedRoot = (Resolve-Path $Root).Path
$pagesPath = Join-Path $resolvedRoot "pages"
$jsPath = Join-Path $resolvedRoot "js"
$manifestPath = Join-Path $jsPath "slides-manifest.js"

$null = New-Item -ItemType Directory -Path $jsPath -Force

function ConvertTo-NormalizedText {
    param(
        [AllowNull()]
        [string]$Text
    )

    if ([string]::IsNullOrWhiteSpace($Text)) {
        return ""
    }

    $withoutTags = [regex]::Replace($Text, "<[^>]+>", " ")
    $decoded = [System.Net.WebUtility]::HtmlDecode($withoutTags)
    return ([regex]::Replace($decoded, "\s+", " ")).Trim()
}

function Get-SlideMetadata {
    param(
        [string]$FolderPath,
        [string]$IndexPath,
        [string]$FolderName
    )

    $content = Get-Content -Path $IndexPath -Raw -Encoding utf8
    $config = Get-SlideConfig -FolderPath $FolderPath -FolderName $FolderName
    $title = ConvertTo-NormalizedText(([regex]::Match($content, "(?is)<title[^>]*>(.*?)</title>")).Groups[1].Value)
    $headline = ConvertTo-NormalizedText(([regex]::Match($content, "(?is)<h1[^>]*>(.*?)</h1>")).Groups[1].Value)

    if (-not $headline) {
        $headline = ConvertTo-NormalizedText(([regex]::Match($content, "(?is)<h2[^>]*>(.*?)</h2>")).Groups[1].Value)
    }

    $classAttributes = [regex]::Matches($content, "(?is)<[^>]+\bclass\s*=\s*[""']([^""']*)[""'][^>]*>")
    $slideCount = 0

    foreach ($match in $classAttributes) {
        $classList = $match.Groups[1].Value -split "\s+" | Where-Object { $_ }
        if ($classList -contains "slide") {
            $slideCount++
        }
    }

    if (-not $title) {
        $title = $config.Title
    }

    if ($config.Exists -and $config.Title) {
        $title = $config.Title
    }

    if (-not $headline -or $headline -eq $title) {
        $headline = $config.Summary
    }

    if ($config.Exists -and $config.Summary) {
        $headline = $config.Summary
    }

    return [pscustomobject]@{
        Title = $title
        Summary = $headline
        SlideCount = $slideCount
    }
}

$manifestItems = @(
    if (Test-Path $pagesPath) {
        Get-ChildItem -Path $pagesPath -Directory |
            Where-Object { $_.Name -like "slides-*" } |
            Sort-Object LastWriteTime -Descending |
            ForEach-Object {
                $scaffoldResult = Ensure-SlideScaffold -FolderPath $_.FullName
                $indexPath = Join-Path $_.FullName "index.html"
                $configPath = Join-Path $_.FullName "deck.json"

                if (-not (Test-Path $indexPath)) {
                    return
                }

                $metadata = Get-SlideMetadata -FolderPath $_.FullName -IndexPath $indexPath -FolderName $_.Name
                $timestamps = @(
                    $_.LastWriteTime
                )

                if (Test-Path $indexPath) {
                    $timestamps += (Get-Item $indexPath).LastWriteTime
                }

                if (Test-Path $configPath) {
                    $timestamps += (Get-Item $configPath).LastWriteTime
                }

                [pscustomobject]@{
                    folder = $_.Name
                    href = "./pages/$($_.Name)/"
                    title = $metadata.Title
                    summary = $metadata.Summary
                    slideCount = $metadata.SlideCount
                    updatedAt = ($timestamps | Sort-Object -Descending | Select-Object -First 1).ToString("o")
                    generated = [bool]($scaffoldResult -and $scaffoldResult.Created)
                }
            }
    }
)

$manifestJson = ConvertTo-Json -InputObject @($manifestItems) -Depth 4
$manifestContent = @(
    "// Auto-generated by scripts/update-slides-manifest.ps1"
    "window.SLIDES_MANIFEST = $manifestJson;"
) -join [Environment]::NewLine

Set-Content -Path $manifestPath -Value $manifestContent -Encoding utf8

Write-Host "Manifesto atualizado: $($manifestItems.Count) apresentacao(oes) encontradas."
